rails/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/', to: 'cookies_storage#index'
  post '/', to: 'cookies_storage#create'
  delete '/delete/:key', to: 'cookies_storage#destroy', as: 'delete'
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/app/controllers/cookies_storage_controller.rb
class CookiesStorageController < ApplicationController

    def index
        @stored_cookies = cookies .reject { |k,v| k == '_simple_cookie_storage_session'}
    end

    def create
        key = params[:key].gsub(" ", "_")
        value = params[:value]
    
        cookies[key] = value
    
        redirect_to '/'
      end

      def destroy
        cookies.delete params[:key]
        redirect_to '/'
      end

end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/views/cookies_storage/index.html.erb
<h1> Add a new Key-Value Pair </h1>

<%= form_tag '/', method: :post do %>
    <p>
      <%= label_tag :key, 'Key' %><br>
      <%= text_field_tag :key %>
    </p>
  
    <p>
      <%= label_tag :value, 'Value' %><br>
      <%= text_field_tag :value %>
    </p>
  
    <%= submit_tag 'Add' %>
<% end %>

<h1> Storage </h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <% @stored_cookies.each do |key, value| %>
      <tr>
        <td><%= key %></td>
        <td><%= value %></td>
        <td><%= button_to 'Delete', delete_path(key.gsub("+", " ")), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCookieStorage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>